spring.application.name=barberflow
spring.config.import=optional:file:.env
# Puerto del servidor backend
server.port=8080

# Configuración de MySQL usando variables de entorno
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# (Pon tu contraseña de MySQL arriba si tienes una, si usas XAMPP suele ir vacío)

# Hibernate y creación automática de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO (GMAIL)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# REEMPLAZA ESTO con el correo que enviará los mensajes
spring.mail.username=barberflow111222@gmail.com

# REEMPLAZA ESTO con la contraseña de 16 letras (SIN ESPACIOS)
spring.mail.password=lkfjzfihmryiqpsc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true